spring:
  r2dbc:
      url: r2dbc:${DATABASE_URL}

  flyway:
    baseline-on-migrate: true
    baseline-version: 0

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${SECURITY_OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${SECURITY_OAUTH2_GOOGLE_CLIENT_SECRET}
          facebook:
            client-id: ${SECURITY_OAUTH2_FACEBOOK_CLIENT_ID}
            client-secret: ${SECURITY_OAUTH2_FACEBOOK_CLIENT_SECRET}
          github:
            client-id: ${SECURITY_OAUTH2_GITHUB_CLIENT_ID}
            client-secret: ${SECURITY_OAUTH2_GITHUB_CLIENT_SECRET}
          vk:
            clientName: VK
            client-id: ${SECURITY_OAUTH2_VK_CLIENT_ID}
            client-secret: ${SECURITY_OAUTH2_VK_CLIENT_SECRET}
            authorizationGrantType: authorization_code
            clientAuthenticationMethod: post
            scope: email
            redirectUri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
        provider:
          vk:
            authorizationUri: https://oauth.vk.com/authorize
            tokenUri: https://oauth.vk.com/access_token
            userInfoUri: https://api.vk.com/method/users.get
            userNameAttribute: id

management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        include: info,health,metrics,bus-refresh

info:
  application:
    name: Orchestra
    version: 0.0.1-SNAPSHOT

application:
  security:
    authentication:
      access-token:
        # seven days
        validity-seconds: 604800
        signing-key: ${SECURITY_ACCESS_TOKEN_SIGNING_KEY}
