spring:
  r2dbc:
    url: r2dbc:${DATABASE_URL}

  flyway:
    baseline-on-migrate: true
    baseline-version: 0

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${SECURITY_OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${SECURITY_OAUTH2_GOOGLE_CLIENT_SECRET}
          facebook:
            client-id: ${SECURITY_OAUTH2_FACEBOOK_CLIENT_ID}
            client-secret: ${SECURITY_OAUTH2_FACEBOOK_CLIENT_SECRET}
          github:
            client-id: ${SECURITY_OAUTH2_GITHUB_CLIENT_ID}
            client-secret: ${SECURITY_OAUTH2_GITHUB_CLIENT_SECRET}
          vk:
            client-name: VK
            client-id: ${SECURITY_OAUTH2_VK_CLIENT_ID}
            client-secret: ${SECURITY_OAUTH2_VK_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            client-authentication-method: post
            scope: email
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
        provider:
          vk:
            authorization-uri: https://oauth.vk.com/authorize
            token-uri: https://oauth.vk.com/access_token
            user-info-uri: https://api.vk.com/method/users.get
            user-name-attribute: id

        redirect-uri-template: 'http://localhost:4200/{[a-z]{2}}/oauth2/authorization/callback'


  jackson.visibility:
    getter: none
    is-getter: none
    setter: none
    field: any

  mail:
    protocol: smtps
    host: smtp.gmail.com
    port: 465
    username: ${SECURITY_MAIL_USERNAME}
    password: ${SECURITY_MAIL_PASSWORD}
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      starttls.required: true
      ssl.enable: true
    test-connection: true

  messages.fallback-to-system-locale: false

management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        include: info,health,metrics

info:
  application:
    name: Orchestra
    version: 0.0.1-SNAPSHOT
    url: http://localhost:4200

application:
  security.authentication.access-token:
    # seven days
    validity-seconds: 604800
    signing-key: ${SECURITY_ACCESS_TOKEN_SIGNING_KEY}

server.error:
  include-message: always
  include-binding-errors: always
